### ISSUE TITLE
Text falls out of container

### ISSUE THREAD

**Issue by Robinfr** [fazouane-marouane/fancy-textfill#1]
The entire purpose of this library is to keep the text inside the container, yet it falls outside of the container in the example.

![text_falls_out](https://cloud.githubusercontent.com/assets/4158484/22887520/b30fedc2-f202-11e6-9846-66b7feea57ac.png)

This happens because the font size is rounded to the nearest whole number, I suggest rounding it down before setting it.

**Comment by fazouane-marouane** [comment]
Your PR has been merged. Thanks again :smile:
