### ISSUE TITLE
How to import as ES6 module

### ISSUE THREAD

**Issue by edanweis** [fazouane-marouane/fancy-textfill#3]
Hi can you help me import this module as ES6? I'm using Vue.js. ie: 

`import fancyTextFill from 'fancy-textfill'`

Thanks

**Comment by fazouane-marouane** [comment]
Hello
I'm looking into this. I'll have a fix this week. I'll post an update once it's ready.

**Comment by fazouane-marouane** [comment]
I've published a new version. Can you confirm that it fixes your issue.

**Comment by fazouane-marouane** [comment]
It's all good now. As of version 1.2.3, the lib provides umd builds and ES2015 modules.
I also updated the README.
Feel free to comment or reopen if the issue persists.
