### ISSUE TITLE
Downloading fancy-text-fill.js file

### ISSUE THREAD

**Issue by DMeechan** [fazouane-marouane/fancy-textfill#4]
Where can I find the fancy-text-fill.js file to download directly without using npm? 

Thanks!

**Comment by fazouane-marouane** [comment]
Hi!

You can find it here: [https://unpkg.com/fancy-textfill/dist/fancy-text-fill.js](https://unpkg.com/fancy-textfill/dist/fancy-text-fill.js)
If you're looking for the jquery plugin: [https://unpkg.com/fancy-textfill/dist/fancy-text-fill.jQuery.js](https://unpkg.com/fancy-textfill/dist/fancy-text-fill.jQuery.js)

**Comment by fazouane-marouane** [comment]
I updated the README with the information provided in my last comment.
Feel free to comment here if you are still experiencing issues regarding usages of fancy-textfill without npm.
