### ISSUE TITLE
require("jquery")

### ISSUE THREAD

**Issue by kringkaste** [fazouane-marouane/fancy-textfill#5]
Hello,

you require jQuery with

`require("jQuery");`

instead of

`require("jquery");`

and so automatic, recursive resolving doesn't work, because the official jquery package is "jquery" and not "jQuery", which is outdated.

Cheers
Tom

**Comment by fazouane-marouane** [comment]
Thanks for the explanation. I'll fix that in the next release!

**Comment by fazouane-marouane** [comment]
This is fixed in version 1.2.2

**Comment by fazouane-marouane** [comment]
I'm reopening this issue as the jquery plugin doesn't seem to work with a basic app bootstrapped with a create-react-app

**Comment by fazouane-marouane** [comment]
It's all good now. As of version 1.2.3, the lib provides umd builds and ES2015 modules.
I also updated the README.
Feel free to comment or reopen if the issue persists.

**Comment by kringkaste** [comment]
Hey, this far better! Thanks. To use your plugin with browerify, I have to add

`"browserify": {
    "transform": [["babelify", { "presets": ["es2015"] }]]
}`

to your package.json and import the index.js and add the jquery function from your jquery.plugin.js:

`
var fillParentContainer = require('fancy-textfill');
$.fn.fancyTextFill = function (opts) {
    this.toArray().forEach(function (el) { return fillParentContainer(el, opts); });
};
`

Maybe you could add the browserify option to your package.json?

**Comment by fazouane-marouane** [comment]
Yes of course. Do you have a test/toy project I can use to reproduce?

**Comment by fazouane-marouane** [comment]
Hello I've pushed a new version with the changes you proposed. Can you check whether it's all good now?

Also, is there a reason you copy the content of `jquery.plugin.js` instead of using `require('fancy-textfill/es2015/jquery.plugin');` ?
